sources:
  - name: Covent Garden Market
    abbrev: CGM
    pages:
      - downtown
      - adult
    url: https://coventmarket.com/events/
    debug_url: "cgm.html"
    finders:
      main:
        css: "section.tile-callout-cards"
      events:
        css: "div.grid-item a"
      link:
        attr: "href"
        methods: "value"
      title:
        css: "h3.event-title"
        methods: "text"
      date:
        css: "div.event-date-time strong"
        methods: "text"
        # removes the trailing end date
        replace: "-.*$"
      time:
        css: "div.event-date-time div"
        methods: "text"
        # removes the trailed end time
        replace: "-.*$"
  - name: Aeolian Hall
    abbrev: Aeol
    pages:
      - downtown
      - entertainment
      - adult
    url: https://aeolianhall.ca/events/
    debug_url: "ah.html"
    finders:
      main:
        css: "section.events-feed"
      events:
        css: "div.event-tile"
      link:
        css: "a.link-wrap"
        attr: "href"
        methods: "value"
      title:
        css: "div.event-title"
        methods: "text"
        # strips leading and trailing whitespace
        replace:
          - "^\\s+"
          - "\\s+$"
      date:
        css: "span.event-date"
        methods: "text"
        # removes the leading day of the week
        replace: "^\\S+ "
      time:
        css: "span.event-time"
        methods: "text"
  - name: Museum London
    abbrev: Museum
    pages:
      - downtown
      - entertainment
      - culture
      - adult
    url: https://museumlondon.ca/programs-events
    page_suffix: /p
    first_page: 1
    max_page: 5
    debug_url: ml.html
    debug_page_suffix: _p
    finders:
      main:
        css: div.event
      events:
        css: div.col-xs-9
      link:
        css: a.num
        attr: href
        methods: value
      title:
        css: a.num h3
        methods: text
      datetime:
        css: span.event-date
        methods: text
        # remove leading day of the week
        replace: "^\\S+ "
  - name: London Music Hall
    abbrev: LMH
    pages:
      - downtown
      - entertainment
      - adult
    url: http://londonmusichall.com/upcoming-events/
    debug_url: lmh.html
    finders:
      main:
        css: div.events
      events:
        css: div.event
      link:
        css: div.event-info h2 a
        attr: href
        methods: value
      title:
        css: div.event-info h2 a
        methods: text
      date:
        css: div.event-info div.date
        methods: text
      time:
        css: div.event-info div.times
        methods: text
        # remove extraneous crap
        replace:
          - "Doors:"
          - "/\\s*Show:.*$"
  - name: Budweiser Gardens
    abbrev: BudG
    pages:
      - downtown
      - entertainment
      - adult
    url: https://www.budweisergardens.com/events
    debug_url: bg.html
    finders:
      main:
        css: div.m-eventList
      events:
        css: div.m-eventItem
      link:
        css: h3.m-eventItem__title a
        attr: href
        methods: value
      title:
        css: h3.m-eventItem__title a
        methods: text
      date:
        css: div.m-eventItem__date
        methods: text
        # remove last word (day of week)
        replace: "\\S+\\s*$"
  # - name: Wolf Performance Hall
  #   abbrev: Wolf
  #   pages:
  #     - downtown
  #     - entertainment
  #     - adult
  #   url: https://www.lpl.ca/services-spaces/featured-spaces/wolf-performance-hall
  #   debug_url: wph.html
  #   finders:
  #     main:
  #       css: div.views-view-grid
  #     events:
  #       css: a.teaser-card--event
  #     link:
  #       attr: href
  #       methods: value
  #     title:
  #       attr: title
  #       methods: value
  #     date:
  #       css: div.teaser-card__event-date div
  #       methods:
  #         - first
  #         - text
  #     time:
  #       css: div.teaser-card__event-date div
  #       methods:
  #         - pop
  #         - text
  #       # remove end time
  #       replace: "- \\s*.*"
  - name: Don Wright Faculty of Music
    abbrev: FMus
    pages:
      - entertainment
      - adult
    url: http://www.events.westernu.ca/events/music/
    debug_url: dwfm.html
    finders:
      main:
        css: "div#mainCol"
      date_containers:
        css: div.day
      date:
        css: h2
        methods: text
        # remove leading day of week
        replace: "^\\S+\\s+"
      events:
        css: div.detailColFull
      link:
        css: div.detailColRight a
        attr: href
        methods: value
      title:
        css: div.detailColRight a
        methods: text
      time:
        css: div.detailColLeft
        methods: text
  - name: Grand Theatre
    abbrev: Grand
    pages:
      - downtown
      - entertainment
      - adult
    url: https://www.grandtheatre.com/events
    debug_url: grand.html
    finders:
      main:
        css: div.shows
      events:
        css: article
      link:
        css: a
        attr: href
        methods: value
      title:
        css: div.cont span
        methods: text
      date:
        css: div.field-date
        methods: text
  - name: "London Children's Museum"
    abbrev: CMus
    pages:
      - downtown
      - kids
    url: https://www.londonchildrensmuseum.ca/events
    page_suffix: ?page=
    first_page: 0
    max_page: 10
    debug_url: lcm.html
    debug_page_suffix: ?page=
    finders:
      main:
        css: div.views-view-grid
      events:
        css: div.views-col
      link:
        css: div.views-field-title a
        attr: href
        methods: value
        replace: "\\n"
      title:
        css: div.views-field-title a
        methods: text
        replace: "\\n"
      datetime:
        css: div.views-field-field-date
        methods: text
        replace: "\\n"
      filters: # exclude closed days
        - match:
            css: div.views-field-title a
            methods: text
          rules:
            - exclude: CLOSED
  - name: Information London
    abbrev: Info
    pages:
      - downtown
      - community
      - adult
    url: https://www.informationlondon.ca/Event/List
    debug_url: il.html
    finders:
      main:
        css: table.tablesorter tbody
      events:
        css: a.event-div
      link:
        attr: href
        methods: value
      title:
        css: div.event-info li.event-title
        methods: text
        replace: "\\n"
        replace: "^\\s+"
      date:
        css: div.date-of-event
        methods: text
        replace:
          - "\\r"
          - "\\n"
          - "\\s*\\S+\\s*$"
      time:
        css: ul.event-details
        methods: text
        replace:
          - "\\n"
          - " - .*"
  - name: Tourism London
    abbrev: Tour
    pages:
      - adult
    url: https://www.londontourism.ca/events/all-events
    page_suffix: /page/
    max_page: 30
    debug_url: tour.html
    debug_page_suffix: _page_
    finders:
      main:
        css: ul.eventCarousel
      events:
        css: li.before-slide a
      link:
        attr: href
        methods: value
      title:
        css: div.description h3
        methods: text
      date:
        css: div.description time
        methods: text
        replace:
          - "^(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday),\\s+"
          - ["(\\w+)\\s+(\\d+)\\s+-\\s+(\\d+)", "\\1 \\2 - \\1 \\3"]
      filters: # exclude events that are already available from another source
        - match:
            css: div.description p.location
            methods: text
          rules:
            - exclude: "London Children's Museum"
            - exclude: "London Knights"
            - exclude: "London Music Hall"
            - exclude: "Rum Runners"
            - exclude: "Eldon House"
            - exclude: "Aeolian Hall"
            - exclude: "Covent Garden Market"
            - exclude: "Don Wright Faculty"
            - exclude: "Museum London"
            #- exclude: "Wolf Performance"
            - exclude: "Museum London"
  - name: Eldon House
    abbrev: Eldon
    pages:
      - community
      - downtown
      - adult
    url: https://eldonhouse.ca/events/
    debug_url: eldon.html
    finders:
      main:
        css: div.elementor-posts-container
      events:
        css: div.elementor-element-58e298a
      link:
        css: div.elementor-button-wrapper a.elementor-button
        attr: href
        methods: value
      title:
        css: div.elementor-element-ad95776 h3.elementor-heading-title
        methods: text
      date:
        css: div.elementor-element-c029367
        methods: text
        replace:
          - "^[\\r\\n\\t]*"
          - "(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday),\\s+"
          - "[\\r\\n\\t].*$"
          - ",\\s*\\d{1,2}:.*$"
          - ",\\s*Drop in.*"
      range-sep: " (?:to|and) "
  - name: Thames Valley District School Board
    abbrev: TVDSB
    pages:
      - community
      - adult
    url: https://calendar.tvdsb.ca/
    debug_url: tvdsb.html
    finders:
      main:
        css: div.calendar-list-container
      events:
        css: div.calendar-list-info
      link:
        css: a.calendar-list-title
        attr: href
        methods: value
      title:
        css: a.calendar-list-title
        methods: text
        replace:
          - "^\\s*"
          - "\\s*$"
      datetime:
        css: div.calendar-list-time
        methods: text
        replace:
          - "^\\s*"
          - "\\s*$"
          - "^\\S+\\s+"
          - [ "\\s+", " " ]
          - ["-", "@"]
  - name: London City Government Calendar
    abbrev: City
    pages:
      - community
      - adult
    url: https://london.ca/government/calendar
    page_suffix: "?page="
    first_page: 0
    max_page: 10
    debug_url: city.html
    debug_page_suffix: "?page="
    finders:
      main:
        css: div.view-events div.view-rows
      events:
        css: article.node--type-event div.teaser
      link:
        css: h2.teaser__title a
        attr: href
        methods: value
      title:
        css: h2.teaser__title a span.field--name-title
        methods: text
        replace:
          - "^\\s*"
          - "\\s*$"
      datetime:
        css: div.teaser__date time.datetime
        attr: datetime
        methods: value
      range-sep: "DUMMY" # just forces it not to split
  - name: Centennial Hall
    abbrev: Cent
    home: https://centennialhall.london.ca/london-event-listings.html
    note: "Not supported: too difficult to scan website automatically"
  - name: 100 Kellogg Lane
    abbrev: 100K
    home: https://100kellogglane.com/
    note: "Not supported: no events listing"
