# in the finders below, `main` finds the document section containing the list of events, `events` finds the list
# of events, and in each event, `link` finds the URL to the web page, `title` finds the title text, `date` finds
# just the datetext, `time` just the time text, `datetime` finds both if they are smashed together`
#
# In each finder, `css` searches by CSS selector and `attr` fetches the element's attribute,
# and the optional `methods` is a Nokogiri method to call on the returning value, either a string or array
#
sources:
  - name: Centennial Hall
    abbrev: Cent
    home: https://centennialhall.london.ca/london-event-listings.html
    note: "Not supported: too difficult to scan website automatically"
  - name: 100 Kellogg Lane
    abbrev: 100K
    home: https://100kellogglane.com/
    note: "Not supported: no events listing"
  - name: Covent Garden Market
    abbrev: CGM
    tags:
      - Municipal
      - Downtown
    url: https://coventmarket.com/events/
    debug_url: "cgm.html"
    home: https://coventmarket.com/
    finders:
      main:
        css: "section.tile-callout-cards"
      events:
        css: "div.grid-item a"
      link:
        attr: "href"
        methods: "value"
      title:
        css: "h3.event-title"
        methods: "text"
      date:
        css: "div.event-date-time strong"
        methods: "text"
        # removes the trailing end date
        replace: "-.*$"
      time:
        css: "div.event-date-time div"
        methods: "text"
        # removes the trailed end time
        replace: "-.*$"
  - name: Aeolian Hall
    abbrev: Aeol
    tags:
      - Downtown
      - Culture
    url: https://aeolianhall.ca/events/
    debug_url: "ah.html"
    home: https://aeolianhall.ca/
    finders:
      main:
        css: "section.events-feed"
      events:
        css: "div.event-tile"
      link:
        css: "a.link-wrap"
        attr: "href"
        methods: "value"
      title:
        css: "div.event-title"
        methods: "text"
        # strips leading and trailing whitespace
        replace:
          - "^\\s+"
          - "\\s+$"
      date:
        css: "span.event-date"
        methods: "text"
        # removes the leading day of the week
        replace: "^\\S+ "
      time:
        css: "span.event-time"
        methods: "text"
  - name: Museum London
    abbrev: Museum
    tags:
      - Downtown
      - Culture
      - Education
    url: https://museumlondon.ca/programs-events
    debug_url: ml.html
    home: https://museumlondon.ca/
    finders:
      main:
        css: div.event
      events:
        css: div.col-xs-9
      link:
        css: a.num
        attr: href
        methods: value
      title:
        css: a.num h3
        methods: text
      datetime:
        css: span.event-date
        methods: text
        # remove leading day of the week
        replace: "^\\S+ "
  - name: London Music Hall
    abbrev: LMH
    tags:
      - Downtown
      - Culture
    url: http://londonmusichall.com/upcoming-events/
    debug_url: lmh.html
    home: http://londonmusichall.com/
    finders:
      main:
        css: div.events
      events:
        css: div.event
      link:
        css: div.event-info h2 a
        attr: href
        methods: value
      title:
        css: div.event-info h2 a
        methods: text
      date:
        css: div.event-info div.date
        methods: text
      time:
        css: div.event-info div.times
        methods: text
        # remove extraneous crap
        replace:
          - "Doors:"
          - "/\\s*Show:.*$"
  - name: Budweiser Gardens
    abbrev: BudG
    tags:
      - Downtown
    url: https://www.budweisergardens.com/events
    debug_url: bg.html
    home: https://www.budweisergardens.com/
    finders:
      main:
        css: div.m-eventList
      events:
        css: div.m-eventItem
      link:
        css: h3.m-eventItem__title a
        attr: href
        methods: value
      title:
        css: h3.m-eventItem__title a
        methods: text
      date:
        css: div.m-eventItem__date
        methods: text
        # remove last word (day of week)
        replace: "\\S+\\s*$"
  - name: Wolf Performance Hall
    abbrev: Wolf
    tags:
      - Downtown
      - Culture
    url: https://www.lpl.ca/services-spaces/featured-spaces/wolf-performance-hall
    debug_url: wph.html
    home: https://www.lpl.ca/services-spaces/featured-spaces/wolf-performance-hall
    finders:
      main:
        css: div.views-view-grid
      events:
        css: a.teaser-card--event
      link:
        attr: href
        methods: value
      title:
        attr: title
        methods: value
      date:
        css: div.teaser-card__event-date div
        methods:
          - first
          - text
      time:
        css: div.teaser-card__event-date div
        methods:
          - pop
          - text
        # remove end time
        replace: "- \\s*.*"
  - name: Don Wright Faculty of Music
    abbrev: FMus
    tags:
      - Culture
    url: http://www.events.westernu.ca/events/music/
    debug_url: dwfm.html
    home: http://www.events.westernu.ca/events/music/
    finders:
      main:
        css: "div#mainCol"
      date_containers:
        css: div.day
      date:
        css: h2
        methods: text
        # remove leading day of week
        replace: "^\\S+\\s+"
      events:
        css: div.detailColFull
      link:
        css: div.detailColRight a
        attr: href
        methods: value
      title:
        css: div.detailColRight a
        methods: text
      time:
        css: div.detailColLeft
        methods: text
  - name: Grand Theatre
    abbrev: Grand
    tags:
      - Downtown
      - Culture
    url: https://www.grandtheatre.com/events
    debug_url: grand.html
    home: https://www.grandtheatre.com/
    finders:
      main:
        css: div.shows
      events:
        css: article
      link:
        css: a
        attr: href
        methods: value
      title:
        css: div.cont span
        methods: text
      date:
        css: div.field-date
        methods: text
  - name: "London Children's Museum"
    abbrev: CMus
    tags:
      - Downtown
      - Education
    url: https://www.londonchildrensmuseum.ca/events
    debug_url: lcm.html
    home: https://www.londonchildrensmuseum.ca/
    finders:
      main:
        css: div.views-view-grid
      events:
        css: div.views-col
      link:
        css: div.views-field-title a
        attr: href
        methods: value
        replace: "\\n"
      title:
        css: div.views-field-title a
        methods: text
        replace: "\\n"
      datetime:
        css: div.views-field-field-date
        methods: text
        replace: "\\n"
  - name: Information London
    abbrev: Info
    tags:
      - Downtown
      - Community
    url: https://www.informationlondon.ca/Event/List
    debug_url: il.html
    home: https://www.informationlondon.ca/
    finders:
      main:
        css: table.tablesorter tbody
      events:
        css: a.event-div
      link:
        attr: href
        methods: value
      title:
        css: div.event-info li.event-title
        methods: text
        replace: "\\n"
        replace: "^\\s+"
      date:
        css: div.date-of-event
        methods: text
        replace:
          - "\\r"
          - "\\n"
          - "\\s*\\S+\\s*$"
      time:
        css: ul.event-details
        methods: text
        replace:
          - "\\n"
          - " - .*"
  - name: Tourism London
    abbrev: Tour
    tags:
      - Community
    url: https://www.londontourism.ca/events/all-events
    debug_url: tour.html
    home: https://www.londontourism.ca/
    finders:
      main:
        css: ul.eventCarousel
      events:
        css: li.before-slide a
      link:
        attr: href
        methods: value
      title:
        css: div.description h3
        methods: text
      date:
        css: div.description time
        methods: text
        replace:
          - "^(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday),\\s+"
          - ["(\\w+)\\s+(\\d+)\\s+-\\s+(\\d+)", "\\1 \\2 - \\1 \\3"]
      filters: # exclude events that are already available from another source
        - match:
            css: div.description p.location
            methods: text
          rules:
            - exclude: "London Children's Museum"
            - exclude: "London Knights"
            - exclude: "London Music Hall"
            - exclude: "Eldon House"
            - exclude: "Aeolian Hall"
            - exclude: "Covent Garden Market"
            - exclude: "Don Wright Faculty"
            - exclude: "Museum London"
            #- exclude: "Wolf Performance"
            - exclude: "Museum London"
  - name: Eldon House
    abbrev: Eldon
    tags:
      - Community
      - Downtown
    url: https://eldonhouse.ca/events/
    debug_url: eldon.html
    home: https://eldonhouse.ca/
    finders:
      main:
        css: div.elementor-posts-container
      events:
        css: div.elementor-element-58e298a
      link:
        css: div.elementor-button-wrapper a.elementor-button
        attr: href
        methods: value
      title:
        css: div.elementor-element-ad95776 h3.elementor-heading-title
        methods: text
      date:
        css: div.elementor-element-c029367
        methods: text
        replace:
          - "^[\\r\\n\\t]*"
          - "(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday),\\s+"
          - "[\\r\\n\\t].*$"
          - ",\\s*\\d{1,2}:.*$"
          - ",\\s*Drop in.*"
      range-sep: " (?:to|and) "
