# in the finders below, `main` finds the document section containing the list of events, `events` finds the list
# of events, and in each event, `link` finds the URL to the web page, `title` finds the title text, `date` finds
# just the datetext, `time` just the time text, `datetime` finds both if they are smashed together`
#
# In each finder, `css` searches by CSS selector and `attr` fetches the element's attribute,
# and the optional `methods` is a Nokogiri method to call on the returning value, either a string or array
#
output_file: ../event-list-site/content/index.md
abbrev_file: ../event-list-site/content/about.md
sources:
  - name: Covent Garden Market
    abbrev: CGM
    tags:
      - Municipal
      - Downtown
    #url: https://coventmarket.com/events/
    url: "cgm.html"
    home: https://coventmarket.com/
    finders:
      main:
        css: "section.tile-callout-cards"
      event:
        css: "div.grid-item a"
      link:
        attr: "href"
        methods: "value"
      title:
        css: "h3.event-title"
        methods: "text"
      date:
        css: "div.event-date-time strong"
        methods: "text"
        # removes the trailing end date
        remove: "-.*$"
      time:
        css: "div.event-date-time div"
        methods: "text"
        # removes the trailed end time
        remove: "-.*$"
  - name: Aeolian Hall
    abbrev: AH
    tags:
      - Downtown
      - Culture
    #url: https://aeolianhall.ca/events/
    url: "ah.html"
    home: https://aeolianhall.ca/
    finders:
      main:
        css: "section.events-feed"
      event:
        css: "div.event-tile"
      link:
        css: "a.link-wrap"
        attr: "href"
        methods: "value"
      title:
        css: "div.event-title"
        methods: "text"
        # strips leading and trailing whitespace
        remove:
          - "^\\s+"
          - "\\s+$"
      date:
        css: "span.event-date"
        methods: "text"
        # removes the leading day of the week
        remove: "^\\S+ "
      time:
        css: "span.event-time"
        methods: "text"
  - name: Museum London
    abbrev: ML
    tags:
      - Downtown
      - Culture
    #url: https://museumlondon.ca/programs-events
    url: ml.html
    home: https://museumlondon.ca/
    finders:
      main:
        css: div.event
      event:
        css: div.col-xs-9
      link:
        css: a.num
        attr: href
        methods: value
      title:
        css: a.num h3
        methods: text
      datetime:
        css: span.event-date
        methods: text
        # remove leading day of the week
        remove: "^\\S+ "
  - name: London Music Hall
    abbrev: LMH
    tags:
      - Downtown
      - Culture
    #url: http://londonmusichall.com/upcoming-events/
    url: lmh.html
    home: http://londonmusichall.com/
    finders:
      main:
        css: div.events
      event:
        css: div.event
      link:
        css: div.event-info h2 a
        attr: href
        methods: value
      title:
        css: div.event-info h2 a
        methods: text
      date:
        css: div.event-info div.date
        methods: text
      time:
        css: div.event-info div.times
        methods: text
        # remove extraneous crap
        remove:
          - "Doors:"
          - "/\\s*Show:.*$"
  - name: Budweiser Gardens
    abbrev: BG
    tags:
      - Downtown
    #url: https://www.budweisergardens.com/events
    url: bg.html
    home: https://www.budweisergardens.com/
    finders:
      main:
        css: div.m-eventList
      event:
        css: div.m-eventItem
      link:
        css: h3.m-eventItem__title
        attr: href
        methods: value
      title:
        css: h3.m-eventItem__title a
        methods: text
      date:
        css: div.m-eventItem__date
        methods: text
        # remove last word (day of week)
        remove: "\\S+\\s*$"
